-- Script para verificar el guardado secuencial TAB1 y TAB2
-- Ejecutar DESPUÉS de hacer la prueba manual

-- 1. Ver última contratación modificada (por fecha)
SELECT 
    ID,
    NUM_EXP,
    DNICONT,
    RSBSALBASE,
    RSBPAGEXTRA,
    RSBIMPORTE,
    RSBCOMPCONV AS "RSBCOMPCONV (Calculado)",
    CSTCONT AS "CSTCONT (Calculado)",
    FECHAMODIFICACION
FROM MELANBIDE11_CONTRATACION
WHERE FECHAMODIFICACION IS NOT NULL
ORDER BY FECHAMODIFICACION DESC
FETCH FIRST 5 ROWS ONLY;

-- 2. Ver líneas de desglose de la última contratación
WITH ULTIMA_CONT AS (
    SELECT NUM_EXP, DNICONT
    FROM MELANBIDE11_CONTRATACION
    WHERE FECHAMODIFICACION IS NOT NULL
    ORDER BY FECHAMODIFICACION DESC
    FETCH FIRST 1 ROW ONLY
)
SELECT 
    d.NUM_EXP,
    d.DNICONTRSB,
    d.RSBTIPO AS "TIPO (1=Sal, 2=Extra)",
    d.RSBIMPORTE AS "IMPORTE",
    d.RSBCONCEPTO AS "CONCEPTO (F/V)",
    d.RSBOBSERV AS "OBSERVACIONES"
FROM MELANBIDE11_DESGRSB d
JOIN ULTIMA_CONT u ON 
    TRIM(d.NUM_EXP) = TRIM(u.NUM_EXP) 
    AND UPPER(REPLACE(REPLACE(TRIM(d.DNICONTRSB),' ',''),'-','')) = 
        UPPER(REPLACE(REPLACE(TRIM(u.DNICONT),' ',''),'-',''))
ORDER BY d.RSBTIPO, d.RSBCONCEPTO;

-- 3. Verificar cálculo de RSBCOMPCONV (solo FIJOS)
WITH ULTIMA_CONT AS (
    SELECT NUM_EXP, DNICONT, RSBSALBASE, RSBPAGEXTRA, RSBCOMPCONV, CSTCONT
    FROM MELANBIDE11_CONTRATACION
    WHERE FECHAMODIFICACION IS NOT NULL
    ORDER BY FECHAMODIFICACION DESC
    FETCH FIRST 1 ROW ONLY
),
CALC AS (
    SELECT 
        u.NUM_EXP,
        u.RSBSALBASE AS BASE,
        u.RSBPAGEXTRA AS PAGAS,
        NVL(SUM(CASE 
            WHEN d.RSBTIPO = '1' AND UPPER(TRIM(d.RSBCONCEPTO)) = 'F' 
            THEN NVL(d.RSBIMPORTE, 0) 
            ELSE 0 
        END), 0) AS COMP_FIJOS,
        u.RSBSALBASE + u.RSBPAGEXTRA + 
        NVL(SUM(CASE 
            WHEN d.RSBTIPO = '1' AND UPPER(TRIM(d.RSBCONCEPTO)) = 'F' 
            THEN NVL(d.RSBIMPORTE, 0) 
            ELSE 0 
        END), 0) AS RSBCOMPCONV_ESPERADO,
        u.RSBCOMPCONV AS RSBCOMPCONV_BD,
        u.CSTCONT AS CSTCONT_BD
    FROM ULTIMA_CONT u
    LEFT JOIN MELANBIDE11_DESGRSB d ON 
        TRIM(d.NUM_EXP) = TRIM(u.NUM_EXP) 
        AND UPPER(REPLACE(REPLACE(TRIM(d.DNICONTRSB),' ',''),'-','')) = 
            UPPER(REPLACE(REPLACE(TRIM(u.DNICONT),' ',''),'-',''))
    GROUP BY u.NUM_EXP, u.RSBSALBASE, u.RSBPAGEXTRA, u.RSBCOMPCONV, u.CSTCONT
)
SELECT 
    NUM_EXP,
    BASE,
    PAGAS,
    COMP_FIJOS AS "COMPLEMENTOS FIJOS (de TAB2)",
    RSBCOMPCONV_ESPERADO AS "RSBCOMPCONV ESPERADO",
    RSBCOMPCONV_BD AS "RSBCOMPCONV EN BD",
    CASE 
        WHEN ABS(RSBCOMPCONV_ESPERADO - RSBCOMPCONV_BD) < 0.01 
        THEN '? OK'
        ELSE '? ERROR - Diferencia: ' || TO_CHAR(RSBCOMPCONV_BD - RSBCOMPCONV_ESPERADO, '999999990.99')
    END AS VALIDACION,
    CSTCONT_BD AS "CSTCONT EN BD"
FROM CALC;

-- 4. Ver timestamps de modificación (para confirmar guardado reciente)
SELECT 
    'MELANBIDE11_CONTRATACION' AS TABLA,
    COUNT(*) AS REGISTROS,
    MAX(FECHAMODIFICACION) AS ULTIMA_MODIFICACION
FROM MELANBIDE11_CONTRATACION
UNION ALL
SELECT 
    'MELANBIDE11_DESGRSB' AS TABLA,
    COUNT(*) AS REGISTROS,
    CAST(NULL AS TIMESTAMP) AS ULTIMA_MODIFICACION
FROM MELANBIDE11_DESGRSB;
